Reactivating deploy

diff --git a/solano.yml b/solano.yml
--- a/solano.yml
+++ b/solano.yml
@@ -4,7 +4,7 @@ system:
 environment:
   'DOCKER_APP': 'ci_memes'
   'DEPLOY_DOCKER': 'true'
-#  'DEPLOY_AWS_ECS': 'true'
+  'DEPLOY_AWS_ECS': 'true'
   'AWS_ECS_CLUSTER': 'default'
   'AWS_ECS_SERVICE': 'ci_memes-service'
   'AWS_ECS_TASK_DEFINITION': 'ci_memes'
@@ -21,28 +21,13 @@ timeout_hook: 900
 
 hooks:
   pre_setup: |
-    set -o errexit -o pipefail # Exit on error
-    # Ensure docker login credentials are set
-    if [[ -z "$DOCKER_EMAIL" || -z "$DOCKER_USER" || -z "$DOCKER_PASSWORD" ]]; then
-      echo 'ERROR: The $DOCKER_EMAIL, $DOCKER_USER, and $DOCKER_PASSWORD values are not all set!'
-      exit 1
-    fi
-    # Build container and store its IP address
-    sudo docker login -e=$DOCKER_EMAIL -u=$DOCKER_USER -p=$DOCKER_PASSWORD # Not necessary for public docker repostiories 
-    sudo docker pull ubuntu:14.04
-    sudo docker build -t $DOCKER_USER/$DOCKER_APP:$TDDIUM_SESSION_ID .
-    CID=$(sudo docker run -d --expose=80 $DOCKER_USER/$DOCKER_APP:$TDDIUM_SESSION_ID)
-    echo $CID > $TDDIUM_REPO_ROOT/container-$TDDIUM_SESSION_ID.cid
-    IP_ADDR=$(sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' $CID)
-    echo $IP_ADDR > $TDDIUM_REPO_ROOT/container-$TDDIUM_SESSION_ID.ip
+    set -e # #xit on error
+    ./scripts/docker_build.sh
     # Create test database SQL and install dependencies
     grep -v ^"CREATE DATABASE " create-db.sql | grep -v ^"USE " > create-test-db.sql
     composer install
-  worker_setup: |
-    set -x
-    head -n 50 create-test-db.sql
-    mysql -u$TDDIUM_DB_USER -p$TDDIUM_DB_PASSWORD $TDDIUM_DB_NAME < create-test-db.sql
-#  post_build: ./scripts/solano-deploy.sh 
+  worker_setup: mysql -u$TDDIUM_DB_USER -p$TDDIUM_DB_PASSWORD $TDDIUM_DB_NAME < create-test-db.sql
+  post_build: ./scripts/solano-deploy.sh 
 
 php:
   php_version: "5.6"
